my_work/geekshop/adminapp/urls.py
from django.urls import path

import adminapp.views as adminapp

app_name = 'adminapp'

urlpatterns = [
    path('', adminapp.ShopUserList.as_view(), name='index'),
    path('user/create/', adminapp.ShopUseCreateView.as_view(), name='user_create'),
    path('user/update/<int:pk>/', adminapp.ShopUserUpdateView.as_view(), name='user_update'),
    path('user/delete/<int:pk>/', adminapp.ShopUserDeleteView.as_view(), name='user_delete'),

    path('categories/', adminapp.categories, name='categories'),
    path('categories/create/', adminapp.GenreBooksCreateView.as_view(), name='categories_create'),
    path('categories/update/<int:pk>/', adminapp.GenreBooksUpdateView.as_view(), name='categories_update'),
    path('categories/delete/<int:pk>/', adminapp.GenreBooksDeleteView.as_view(), name='categories_delete'),
    path('categories/<int:pk>/products/', adminapp.category_products, name='category_products'),
    path('product/<int:pk>/', adminapp.ProductDetail.as_view(), name='product_detail'),
    path('categories/<int:pk>/product/create/', adminapp.product_create, name='product_create'),
]

my_work/geekshop/authapp/urls.py
from django.urls import path

import authapp.views as authapp


app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path('register/', authapp.register, name='register'),
    path('update/', authapp.update, name='update'),
]

my_work/geekshop/geekshop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('mainapp.urls', namespace='main')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('adminapp/', include('adminapp.urls', namespace='adminapp')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

my_work/geekshop/adminapp/models.py
from django.db import models

# Create your models here.

my_work/geekshop/adminapp/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.forms import forms, HiddenInput, ModelForm

from mainapp.models import GenreBooks, Book


class AgeValidationMixin:
    def clean_age(self):
        age = self.cleaned_data.get('age')
        if age and age < 18:
            raise forms.ValidationError('вы слишком молоды!')
        return age


class AdminShopUserCreateForm(UserCreationForm, AgeValidationMixin):
    class Meta:
        model = get_user_model()
        fields = ('username', 'first_name', 'last_name', 'password1', 'password2',
                  'email', 'age', 'avatar', 'is_staff', 'is_superuser', 'is_active')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = f'form-control {field_name}'
            field.help_text = ''
            if field_name == 'password':
                field.widget = HiddenInput()


class AdminShopUserUpdateForm(UserChangeForm, AgeValidationMixin):
    class Meta:
        model = get_user_model()
        fields = ('username', 'first_name', 'last_name', 'password', 'email',
                  'age', 'avatar', 'is_staff', 'is_superuser', 'is_active')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = f'form-control {field_name}'
            field.help_text = ''
            if field_name == 'password':
                field.widget = HiddenInput()


class AdminProductCategoryUpdateForm(ModelForm):
    class Meta:
        model = GenreBooks
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = f'form-control {field_name}'


class AdminProductUpdateForm(ModelForm):
    class Meta:
        model = Book
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = f'form-control {field_name}'
            if field_name == 'genre_book':
                field.widget = HiddenInput()

my_work/geekshop/adminapp/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import user_passes_test
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse, reverse_lazy

from adminapp.forms import AdminShopUserCreateForm, AdminShopUserUpdateForm
from django.utils.decorators import method_decorator
from django.views.generic import ListView, CreateView, UpdateView, DeleteView, DetailView

from mainapp.models import GenreBooks, Book

from adminapp.forms import AdminProductCategoryUpdateForm, AdminProductUpdateForm


class SuperUserOnlyMixin:
    @method_decorator(user_passes_test(lambda x: x.is_superuser))
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)


class SetPageTitleMixin:
    page_title = ''

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=None, **kwargs)
        context['page_title'] = self.page_title
        return context


# @user_passes_test(lambda x: x.is_superuser)
# def user_create(request):
#     if request.method == 'POST':
#         user_form = AdminShopUserCreateForm(request.POST, request.FILES)
#         if user_form.is_valid():
#             user_form.save()
#             return HttpResponseRedirect(reverse('adminapp:index'))
#     else:
#         user_form = AdminShopUserCreateForm()
#
#     context = {
#         'page_title': 'админка/пользователи/создание',
#         'form': user_form
#     }
#     return render(request, 'adminapp/user_update.html', context=context)


# @user_passes_test(lambda x: x.is_superuser)
# def index(request):
#     users = get_user_model().objects.all()
#     context = {
#         'page_title': 'админка/пользователи',
#         'object_list': users,
#     }
#     return render(request, 'adminapp/index.html', context=context)

class ShopUserList(SuperUserOnlyMixin, SetPageTitleMixin, ListView):
    model = get_user_model()
    page_title = 'админка/пользователи'


class ShopUseCreateView(SuperUserOnlyMixin, SetPageTitleMixin, CreateView):
    model = get_user_model()
    form_class = AdminShopUserCreateForm
    success_url = reverse_lazy('adminapp:index')
    page_title = 'админка/пользователи/создание'


class ShopUserUpdateView(SuperUserOnlyMixin, SetPageTitleMixin, UpdateView):
    model = get_user_model()
    form_class = AdminShopUserUpdateForm
    success_url = reverse_lazy('adminapp:index')
    page_title = 'админка/пользователи/редактирование'


class ShopUserDeleteView(SuperUserOnlyMixin, SetPageTitleMixin, DeleteView):
    model = get_user_model()
    success_url = reverse_lazy('adminapp:index')
    page_title = 'админка/пользователи/удаление'


# @user_passes_test(lambda x: x.is_superuser)
# def user_update(request, user_pk):
#     user = get_object_or_404(get_user_model(), pk=user_pk)
#     if request.method == 'POST':
#         user_form = AdminShopUserUpdateForm(request.POST, request.FILES, instance=user)
#         if user_form.is_valid():
#             user_form.save()
#             return HttpResponseRedirect(reverse('adminapp:index'))
#     else:
#         user_form = AdminShopUserUpdateForm(instance=user)
#
#     context = {
#         'page_title': 'админка/пользователи/редактирование',
#         'form': user_form
#     }
#     return render(request, 'adminapp/user_update.html', context=context)


# @user_passes_test(lambda x: x.is_superuser)
# def user_delete(request, user_pk):
#     user = get_object_or_404(get_user_model(), pk=user_pk)
#     if not user.is_active or request.method == 'POST':
#         if user.is_active:
#             user.is_active = False
#             user.save()
#         return HttpResponseRedirect(reverse('adminapp:index'))
#
#     context = {
#         'page_title': 'админка/пользователи/удаление',
#         'object': user
#     }
#     return render(request, 'adminapp/user_delete.html', context=context)


@user_passes_test(lambda x: x.is_superuser)
def categories(request):
    items = GenreBooks.objects.all()
    context = {
        'page_title': 'админка/категории',
        'object_list': items,
    }
    return render(request, 'adminapp/categories_list.html', context=context)


class GenreBooksCreateView(SuperUserOnlyMixin, SetPageTitleMixin, CreateView):
    model = GenreBooks
    form_class = AdminProductCategoryUpdateForm
    success_url = reverse_lazy('adminapp:categories')
    page_title = 'админка/категории/создание'


class GenreBooksUpdateView(SuperUserOnlyMixin, SetPageTitleMixin, UpdateView):
    model = GenreBooks
    form_class = AdminProductCategoryUpdateForm
    success_url = reverse_lazy('adminapp:categories')
    page_title = 'админка/категории/редактирование'


class GenreBooksDeleteView(SuperUserOnlyMixin, SetPageTitleMixin, DeleteView):
    model = GenreBooks
    success_url = reverse_lazy('adminapp:categories')
    page_title = 'админка/пользователи/удаление'


@user_passes_test(lambda x: x.is_superuser)
def category_products(request, pk):
    category = get_object_or_404(GenreBooks, pk=pk)
    object_list = category.book_set.all()
    context = {
        'page_title': f'категория {category.genre}/книги',
        'category': category,
        'object_list': object_list
    }
    return render(request, 'adminapp/category_products_list.html', context)


@user_passes_test(lambda x: x.is_superuser)
def product_create(request, pk):
    category = get_object_or_404(GenreBooks, pk=pk)
    if request.method == 'POST':
        form = AdminProductUpdateForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse(
                'adminapp:category_products',
                kwargs={'pk': category.pk}
            ))
    else:
        form = AdminProductUpdateForm(
            initial={
                'genre_book': category,
            }
        )
    context = {
        'page_title': 'продукты/создание',
        'form': form,
        'category': category,
    }
    return render(request, 'adminapp/product_update.html', context)


class ProductDetail(SuperUserOnlyMixin, DetailView):
    model = Book

my_work/geekshop/adminapp/templates/adminapp/base.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <meta charset="utf-8">
    <title>
        {% block title %}
            {{ page_title|title }}
        {% endblock %}
    </title>
    {% block css %}
        <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    {% endblock %}
    {% block js %}
    {% endblock %}
</head>
<body>
<div class="admin_container">
    <div class="h2 text-center head">
        Админка
    </div>
    {% block menu %}
        <div class="admin_menu">
            {% include 'adminapp/includes/inc__menu.html' %}
        </div>
    {% endblock %}

    {% block container %}
    {% endblock %}

</div>
</body>
</html>

my_work/geekshop/adminapp/templates/adminapp/categories.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block container %}
    <div class="users_list">
        <a href="{% url 'adminapp:categories_create' %}" class="btn btn-primary new_user">
            новая категория
        </a>
        {% for category in object_list %}
            <div class="user_record {% if not category.is_active %}not_active{% endif %}">
                <div class="user_role">
                    <a href="{% url 'adminapp:categories_update' category.pk %}" class="btn btn-primary">
                        редактировать
                    </a>
                    <a href="{% url 'adminapp:categories_delete' category.pk %}" class="btn btn-danger">
                        удалить
                    </a>
                </div>
                <div class="user_name">
                    <p><strong>{{ category.genre }}</strong></p>
                </div>
                <div>
                    {{ category.description }}
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

my_work/geekshop/adminapp/templates/adminapp/categories_list.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block container %}
    <div class="users_list">
        <a href="{% url 'adminapp:categories_create' %}" class="btn btn-primary new_user">
            новая категория
        </a>
        {% for category in object_list %}
            <div class="category_record {% if not category.is_active %}not_active{% endif %}">
                <div class="category_name">
                    {{ object.name|title }}
                </div>
                <div class="category_actions">
                     <a href="{% url 'adminapp:category_products' category.pk %}" class="btn btn-primary">
                        товары жанра
                    </a>
                </div>
                    <a href="{% url 'adminapp:categories_update' category.pk %}" class="btn btn-primary">
                        редактировать
                    </a>
                    <a href="{% url 'adminapp:categories_delete' category.pk %}" class="btn btn-danger">
                        удалить
                    </a>
                </div>
                <div class="user_name">
                    <p><strong>{{ category.name }}</strong></p>
                </div>
                <div>
                    {{ category.description }}
                </div>
            </div>
        {% endfor %}
{% endblock %}

my_work/geekshop/adminapp/templates/adminapp/category_products_list.html
{% extends 'adminapp/base.html' %}
{% load static %}


{% block container %}
    <div class="products_list">
        <a class="new_product btn btn-default"
           href="{% url 'adminapp:product_create' category.pk %}">новый продукт</a>

        {% for object in object_list %}
            <div class="product_record {% if not object.is_active %}not_active{% endif %}">
                <img src="/media/{{ object.image|default:'books_images/default.jpg' }}" alt="{{ object.name }}">
                <div class="product_name">
                    {{ object.name|title }}
                </div>
                <div class="product_actions">
                    <button>
                        <a href="{% url 'adminapp:product_detail' pk=object.pk %}">подробнее</a>
                    </button>
                    <button>
                        <a href="{#% url 'adminapp:product_update' object.pk %#}">редактировать</a>
                    </button>
                    <button>
                        <a href="{#% url 'myadmin:product_delete' object.pk %#}">удалить</a>
                    </button>
                </div>
                <div class="summary">
                    <b>цена</b>
                    <p>{{ object.price }} руб</p>
                    <b>количество</b>
                    <p>{{ object.quantity }}</p>
                </div>
                <div class="product_desc">
                    {{ object.short_desc|capfirst }}
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

my_work/geekshop/adminapp/templates/adminapp/product_update.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block menu %}
{% endblock %}

{% block container %}
    <div class="new_category_form">
        <form class="form-horizontal" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <input class="form-control" type="submit" value="сохранить">
        </form>
        <a href="{% url 'adminapp:category_products' category.pk %}"
           class="btn btn-primary form-control last">
            к списку продуктов
        </a>
    </div>
{% endblock %}