my_work/geekshop/authapp/urls.py
from django.urls import path

import authapp.views as authapp


app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path('register/', authapp.register, name='register'),
    path('update/', authapp.update, name='update'),
]

my_work/geekshop/basketapp/urls.py
from django.urls import path

import basketapp.views as basketapp


app_name = 'basketapp'

urlpatterns = [
    path('', basketapp.index, name='index'),
    path('add_book/<int:book_pk>/', basketapp.add_book, name='add_book'),
    path('remove_book/<int:basket_pk>/', basketapp.remove_book, name='remove_book'),
    path('update_book/<int:basket_pk>/<int:qty>/', basketapp.update_book),
]

my_work/geekshop/geekshop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('mainapp.urls', namespace='main')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('adminapp/', include('adminapp.urls', namespace='adminapp')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

my_work/geekshop/basketapp/models.py
from django.contrib.auth import get_user_model
from django.db import models

from mainapp.models import Book


class Basket(models.Model):
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE,
                             related_name='basket')
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    counter = models.IntegerField('количество', default=0)
    add_datetime = models.DateTimeField('время', auto_now_add=True)

    @property
    def book_cost(self):
        return self.book.price * self.counter

my_work/geekshop/basketapp/views.py
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, JsonResponse
from django.shortcuts import render, get_object_or_404

from basketapp.models import Basket
from django.template import loader


@login_required
def index(request):
    basket = request.user.basket.all()

    context = {
        'page_title': 'корзина',
        'basket': basket,
    }
    return render(request, 'basketapp/index.html', context=context)


@login_required
def add_book(request, book_pk):
    basket_item = request.user.basket.filter(
        book_id=book_pk
    ).first()
    if not basket_item:
        basket_item = Basket.objects.create(
            user=request.user,
            book_id=book_pk
        )

    basket_item.counter += 1
    basket_item.save()
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


@login_required
def remove_book(request, basket_pk):
    basket_item = get_object_or_404(Basket, book_id=basket_pk)
    basket_item.delete()
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


@login_required
def update_book(request, basket_pk, qty):
    if request.is_ajax():
        basket_item = Basket.objects.filter(pk=basket_pk).first()
        if not basket_item:
            return JsonResponse(
                {'status': 'error'},
                status_code=404
            )
        if qty <= 0:
            basket_item.delete()
        else:
            basket_item.counter = qty
            basket_item.save()

        basket = request.user.basket.all()
        context = {
            'basket': basket,
        }
        basket_list = loader.render_to_string(
            'basketapp/includes/inc__basket_list.html',
            context=context,
            request=request
        )
        return JsonResponse({
            'status': 'ok',
            'basket_list': basket_list
        })

my_work/geekshop/basketapp/templates/basketapp/includes/inc__basket_list.html
{% load static %}

{% if basket %}
{% for item in basket %}
<div class="basket_record">
    <img src="/media/{{ item.book.image }}" alt="{{ item.book.short_description }}">
    <span class="category_name">{{ item.book.genre_book.genre }}</span>
    <span class="product_name">{{ item.book.name }}</span>
    <span class="product_price">{{ item.book.price }}&nbspруб</span>
    <input type="number" name="{{ item.pk }}" min="0" max="{{ item.book.quantity }}"
           value="{{ item.counter }}">
    <span class="product_cost">{{ item.book_cost }}&nbspруб</span>

    <a href="{% url 'basket:remove_book' basket_pk=item.book.pk %}" class="btn btn-round">
        удалить
    </a>
</div>
{% endfor %}

<div class="basket_summary">
    В корзине {{ user.basket_total_qty }} товара(ов) общей стоимостью
    {{ user.basket_total_cost }} руб
</div>
{% else %}
<h4>Корзина пуста</h4>
{% endif %}

<a href="{% url 'main:index' %}" class="btn btn-round">
    на главную
</a>