my_work/geekshop/authapp/urls.py
from django.urls import path

import authapp.views as authapp


app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path('register/', authapp.register, name='register'),
    path('update/', authapp.update, name='update'),
]

my_work/geekshop/geekshop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('mainapp.urls', namespace='main')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('adminapp/', include('adminapp.urls', namespace='adminapp')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

my_work/geekshop/mainapp/urls.py
from django.urls import path

import mainapp.views as mainapp

app_name = 'mainapp'

urlpatterns = [
    path('', mainapp.index, name='index'),
    path('product/', mainapp.product, name='product'),
    path('contact/', mainapp.contact, name='contact'),
    path('product_details/<int:book_pk>/', mainapp.product_details, name='product_details'),
    path('catalog_page/<int:genre_pk>/', mainapp.catalog_page, name='catalog_page'),
    path('catalog_page/<int:genre_pk>/<int:page_num>/', mainapp.catalog_page, name='catalog_page_pages'),
]

my_work/geekshop/mainapp/models.py
from django.db import models


class GenreBooks(models.Model):
    genre = models.CharField('жанр книги', max_length=64)
    description = models.TextField('Описание жанра', blank=True)
    is_active = models.BooleanField('активность', default=True)

    class Meta:
        verbose_name = 'жанр книг'
        verbose_name_plural = 'жанры книг'
        ordering = ['genre']

    def __str__(self):
        return f'{self.genre}'

    def delete(self, using=None, keep_parents=False):
        self.is_active = False
        self.save()
        return 1, {}


class Book(models.Model):
    genre_book = models.ForeignKey(GenreBooks, on_delete=models.CASCADE)
    name = models.CharField('книга', max_length=64)
    image = models.ImageField(upload_to='books_images', blank=True)
    author = models.CharField('автор', max_length=64)
    description = models.TextField('Описание', blank=True)
    short_description = models.CharField('краткое описание', max_length=64, blank=True)
    price = models.DecimalField('цена', max_digits=7, decimal_places=2, default=0)
    count_page = models.PositiveSmallIntegerField('количество страниц', default=0)
    quantity = models.PositiveIntegerField('количество на складе', default=0)
    is_active = models.BooleanField('активность', default=True)

    class Meta:
        verbose_name = 'книга'
        verbose_name_plural = 'книги'

    def __str__(self):
        return f'{self.name} ({self.genre_book})'

my_work/geekshop/mainapp/views.py
import random

from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.shortcuts import render, get_object_or_404

from mainapp.models import GenreBooks

from mainapp.models import Book


def get_catalog_menu():
    return GenreBooks.objects.all()


def get_hot_book():
    books = Book.objects.all()
    return random.choice(books)


def get_same_books(book):
    return Book.objects.filter(genre_book=book.genre_book).exclude(pk=book.pk)


def index(request):
    links_menu = [
        {'href': 'main:index', 'name': 'главная'},
        {'href': 'main:product', 'name': 'каталог'},
        {'href': 'main:contact', 'name': 'КОНТАКТЫ'},
    ]
    context = {
        'page_title': 'главная',
        'links_menu': links_menu,
    }
    return render(request, 'mainapp/index.html', context=context)


def product(request):
    hot_book = get_hot_book()
    links_menu = [
        {'href': 'main:index', 'name': 'главная'},
        {'href': 'main:product', 'name': 'каталог'},
        {'href': 'main:contact', 'name': 'контакты'},
    ]
    context = {
        'page_title': 'каталог',
        'same_books': get_same_books(hot_book),
        'hot_book': hot_book,
        'links_menu': links_menu,
        'catalog_menu': get_catalog_menu(),
    }
    return render(request, 'mainapp/product.html', context=context)


def contact(request):
    links_menu = [
        {'href': 'main:index', 'name': 'главная'},
        {'href': 'main:product', 'name': 'каталог'},
        {'href': 'main:contact', 'name': 'контакты'},
    ]
    locations = [
        {
            'city': 'Москва',
            'phone': '8(954) 145-45-85',
            'mail': 'moskow@bookshoop.ru',
            'address': 'ул. Ленина 45',
        },
        {
            'city': 'Санкт-Петербург',
            'phone': '8(812)121-21-21',
            'mail': 'spb@bookshoop.ru',
            'address': 'пр. Невский 12',
        },
        {
            'city': 'Барнаул',
            'phone': '8(365) 194-34-12',
            'mail': 'barnaul@bookshoop.ru',
            'address': 'ул. Тракторная 18',
        },
    ]
    context = {
        'page_title': 'контакты',
        'locations': locations,
        'links_menu': links_menu,
    }
    return render(request, 'mainapp/contact.html', context=context)


def catalog_page(request, genre_pk, page_num=1):
    if genre_pk == 0:
        books = Book.objects.all()
    else:
        books = Book.objects.filter(genre_book_id=genre_pk)

    products_paginator = Paginator(books, 2)
    try:
        books = products_paginator.page(page_num)
    except PageNotAnInteger:
        books = products_paginator.page(1)
    except EmptyPage:
        books = products_paginator.page(products_paginator.num_pages)

    links_menu = [
        {'href': 'main:index', 'name': 'главная'},
        {'href': 'main:product', 'name': 'каталог'},
        {'href': 'main:contact', 'name': 'контакты'},
    ]

    context = {
        'page_title': 'каталог',
        'links_menu': links_menu,
        'catalog_menu': get_catalog_menu(),
        'books': books,
        'genre_pk': genre_pk,
    }
    return render(request, 'mainapp/product.html', context=context)


def product_details(request, book_pk):
    item = get_object_or_404(Book, pk=book_pk)

    links_menu = [
        {'href': 'main:index', 'name': 'главная'},
        {'href': 'main:product', 'name': 'каталог'},
        {'href': 'main:contact', 'name': 'контакты'},
    ]

    context = {
        'page_title': 'книга',
        'links_menu': links_menu,
        'catalog_menu': get_catalog_menu(),
        'item': item,
        'book_pk': item.id,
    }
    return render(request, 'mainapp/product_details.html', context=context)

my_work/geekshop/mainapp/templates/mainapp/includes/inc__catalog_menu.html
<ul class="product-menu-ul">
    <li class="product-menu-lict-active">
        <a href="{% url 'main:catalog_page' 0 %}"
           class="{% if request.resolver_match.kwargs.genre_pk == 0 %}
                               product-a
                            {% endif %}">
            ВСЕ
        </a>
    </li>
    {% for item in catalog_menu %}
    <li class="product-menu-lict">
        <a href="{% url 'main:catalog_page' item.pk %}"
           class="{% if request.resolver_match.kwargs.genre_pk == item.pk %}
                               product-a
                            {% endif %}">
            {{ item.genre }}
        </a>
    </li>

    {% endfor %}

</ul>

my_work/geekshop/mainapp/templates/mainapp/includes/inc__main_menu.html
{% load static %}

<div class="header clearfix">
    <a href="#"><img src="{% static 'img/logo.svg' %}" alt="logo"></a>
    <ul class="menu clearfix">
        {% for link in links_menu %}
        <li class="menu-list">
            <a href="{% url link.href %}"
               class="menu-link
{% if request.resolver_match.view_name == link.href or request.resolver_match.url_name == 'catalog_page' and link.name == 'каталог' %}
                               menu-link-active
                            {% endif %}">
                {{ link.name }}
            </a>
        </li>
        {% endfor %}

        {% if user.is_authenticated %}
        <li class="menu-list">
            <a href="{% url 'auth:update' %}" class="menu-link">
                {{ user.first_name|default:'пользователь'|title }}
            </a>
        </li>
        {% endif %}

        {% if user.is_superuser %}
        <li class="menu-list">
            <a href="{% url 'adminapp:index' %}" class="menu-link">
                админка
            </a>
        </li>
        {% endif %}

        <li class="menu-list">
            {% if user.is_authenticated %}

            <a href="{% url 'auth:logout' %}" class="menu-link">выйти</a>
            {% else %}
            <a href="{% url 'auth:login' %}" class="menu-link">вход</a>

            {% endif %}
        </li>


        <li class="menu-list">
            <a href="#" class="menu-search"><img src="{% static 'img/search.svg' %}" alt="logo"></a>
            <a href="{% url 'basket:index' %}" class="menu-search">
                <img src="{% static 'img/basket.png' %}" alt="logo">
                ({{ user.basket_total_cost|floatformat:0 }} руб) {{ user.basket_total_qty }} шт
            </a>
        </li>
    </ul>
</div>