my_work/geekshop/authapp/urls.py
from django.urls import path

import authapp.views as authapp


app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path('register/', authapp.register, name='register'),
    path('update/', authapp.update, name='update'),
]

my_work/geekshop/basketapp/urls.py
from django.urls import path

import basketapp.views as basketapp


app_name = 'basketapp'

urlpatterns = [
    path('', basketapp.index, name='index'),
    path('add_book/<int:book_pk>/', basketapp.add_book, name='add_book'),
    path('remove_book/<int:basket_pk>/', basketapp.remove_book, name='remove_book'),
    path('update_book/<int:basket_pk>/<int:qty>/', basketapp.update_book),
]

my_work/geekshop/geekshop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('mainapp.urls', namespace='main')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('adminapp/', include('adminapp.urls', namespace='adminapp')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

my_work/geekshop/mainapp/urls.py
from django.urls import path

import mainapp.views as mainapp

app_name = 'mainapp'

urlpatterns = [
    path('', mainapp.index, name='index'),
    path('product/', mainapp.product, name='product'),
    path('contact/', mainapp.contact, name='contact'),
    path('product_details/<int:book_pk>/', mainapp.product_details, name='product_details'),
    path('catalog_page/<int:genre_pk>/', mainapp.catalog_page, name='catalog_page'),
    path('catalog_page/<int:genre_pk>/<int:page_num>/', mainapp.catalog_page, name='catalog_page_pages'),
]

my_work/geekshop/mainapp/models.py
from django.db import models


class GenreBooks(models.Model):
    genre = models.CharField('жанр книги', max_length=64)
    description = models.TextField('Описание жанра', blank=True)
    is_active = models.BooleanField('активность', default=True)

    class Meta:
        verbose_name = 'жанр книг'
        verbose_name_plural = 'жанры книг'
        ordering = ['genre']

    def __str__(self):
        return f'{self.genre}'

    def delete(self, using=None, keep_parents=False):
        self.is_active = False
        self.save()
        return 1, {}


class Book(models.Model):
    genre_book = models.ForeignKey(GenreBooks, on_delete=models.CASCADE)
    name = models.CharField('книга', max_length=64)
    image = models.ImageField(upload_to='books_images', blank=True)
    author = models.CharField('автор', max_length=64)
    description = models.TextField('Описание', blank=True)
    short_description = models.CharField('краткое описание', max_length=64, blank=True)
    price = models.DecimalField('цена', max_digits=7, decimal_places=2, default=0)
    count_page = models.PositiveSmallIntegerField('количество страниц', default=0)
    quantity = models.PositiveIntegerField('количество на складе', default=0)
    is_active = models.BooleanField('активность', default=True)

    class Meta:
        verbose_name = 'книга'
        verbose_name_plural = 'книги'

    def __str__(self):
        return f'{self.name} ({self.genre_book})'

my_work/geekshop/mainapp/views.py
import random

from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.shortcuts import render, get_object_or_404

from mainapp.models import GenreBooks

from mainapp.models import Book


def get_catalog_menu():
    return GenreBooks.objects.all()


def get_hot_book():
    books = Book.objects.all()
    return random.choice(books)


def get_same_books(book):
    return Book.objects.filter(genre_book=book.genre_book).exclude(pk=book.pk)


def index(request):
    links_menu = [
        {'href': 'main:index', 'name': 'главная'},
        {'href': 'main:product', 'name': 'каталог'},
        {'href': 'main:contact', 'name': 'КОНТАКТЫ'},
    ]
    context = {
        'page_title': 'главная',
        'links_menu': links_menu,
    }
    return render(request, 'mainapp/index.html', context=context)


def product(request):
    hot_book = get_hot_book()
    links_menu = [
        {'href': 'main:index', 'name': 'главная'},
        {'href': 'main:product', 'name': 'каталог'},
        {'href': 'main:contact', 'name': 'контакты'},
    ]
    context = {
        'page_title': 'каталог',
        'same_books': get_same_books(hot_book),
        'hot_book': hot_book,
        'links_menu': links_menu,
        'catalog_menu': get_catalog_menu(),
    }
    return render(request, 'mainapp/product.html', context=context)


def contact(request):
    links_menu = [
        {'href': 'main:index', 'name': 'главная'},
        {'href': 'main:product', 'name': 'каталог'},
        {'href': 'main:contact', 'name': 'контакты'},
    ]
    locations = [
        {
            'city': 'Москва',
            'phone': '8(954) 145-45-85',
            'mail': 'moskow@bookshoop.ru',
            'address': 'ул. Ленина 45',
        },
        {
            'city': 'Санкт-Петербург',
            'phone': '8(812)121-21-21',
            'mail': 'spb@bookshoop.ru',
            'address': 'пр. Невский 12',
        },
        {
            'city': 'Барнаул',
            'phone': '8(365) 194-34-12',
            'mail': 'barnaul@bookshoop.ru',
            'address': 'ул. Тракторная 18',
        },
    ]
    context = {
        'page_title': 'контакты',
        'locations': locations,
        'links_menu': links_menu,
    }
    return render(request, 'mainapp/contact.html', context=context)


def catalog_page(request, genre_pk, page_num=1):
    if genre_pk == 0:
        books = Book.objects.all()
    else:
        books = Book.objects.filter(genre_book_id=genre_pk)

    products_paginator = Paginator(books, 2)
    try:
        books = products_paginator.page(page_num)
    except PageNotAnInteger:
        books = products_paginator.page(1)
    except EmptyPage:
        books = products_paginator.page(products_paginator.num_pages)

    links_menu = [
        {'href': 'main:index', 'name': 'главная'},
        {'href': 'main:product', 'name': 'каталог'},
        {'href': 'main:contact', 'name': 'контакты'},
    ]

    context = {
        'page_title': 'каталог',
        'links_menu': links_menu,
        'catalog_menu': get_catalog_menu(),
        'books': books,
        'genre_pk': genre_pk,
    }
    return render(request, 'mainapp/product.html', context=context)


def product_details(request, book_pk):
    item = get_object_or_404(Book, pk=book_pk)

    links_menu = [
        {'href': 'main:index', 'name': 'главная'},
        {'href': 'main:product', 'name': 'каталог'},
        {'href': 'main:contact', 'name': 'контакты'},
    ]

    context = {
        'page_title': 'книга',
        'links_menu': links_menu,
        'catalog_menu': get_catalog_menu(),
        'item': item,
        'book_pk': item.id,
    }
    return render(request, 'mainapp/product_details.html', context=context)

my_work/geekshop/mainapp/templates/mainapp/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>{{ page_title|default:'bookshop'|title }}</title>
    {% block css %}
        <link href="https://fonts.googleapis.com/css?family=Montserrat:100,300,400,700" rel="stylesheet">
        <link rel="stylesheet" href="{% static 'css/style.css' %}">
    {% endblock %}
    {% block js %}
    <script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
    {% endblock %}

</head>


<body>
<div class="conteiner">
    {% block conteiner %}

    {% endblock %}
    <div class="clr"></div>
</div>
<div class="center">
    <div class="footer">

        <div class="row rstr-3" id="rstr-id-3">
            <div class="col-4 str-3 rtd-1">© Copyright - BOOKSHOP {% now 'd_m_Y' %}. All Rights Reserved.</div>
            <div class="col-4 rtd-2"><img class="csite" src="{% static 'img/social-links.png' %}" alt="icon"></div>
            <div class="col-4 str-3 rtd-2">Terms & Conditions / Privacy policy & Cookies</div>
        </div>
    </div>
</div>

</body>

</html>

my_work/geekshop/mainapp/templates/mainapp/contact.html
{% extends 'mainapp/base.html' %}
{% load static %}
{% block conteiner %}

<div class="slider-contact padding-site clearfix">
    {% include 'mainapp/includes/inc__main_menu.html' %}
    <div class="contact-us">Наши контакты</div>

</div>
<div class="row main-contact" id="contact-1">
    {% if locations %}
    {% for item in locations %}
    <div class="col-contact">
        <div class="icomoon"><img src="{% static 'img/icomoon.png' %}" alt="icomoon"></div>
        <div class="icomoon-h3">{{ item.city }}</div>
        <div class="icomoon-p">Phone: <br>
            <span class="b-contact">{{ item.phone }}</span> <br>
            Email: <br>
            <span class="b-contact">{{ item.mail }}</span><br>
            Address: <br>{{ item.address }}
        </div>
    </div>
    {% endfor %}


    {% else %}
        <h3>Данные загружаються</h3>
    {% endif %}

</div>


{% endblock %}

my_work/geekshop/mainapp/templates/mainapp/index.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block conteiner %}

<div class="slider padding-site clearfix">
    {% include 'mainapp/includes/inc__main_menu.html' %}
    <div class="slider-text">
        <p class="slider-trending">НОВИНКИ</p>
        <h2 class="slider-h2">бестселлеры</h2>
        <p class="slider-content">Самые покупаемые книги</p> <a href="#" class="buttom">Заказать</a></div>
    <div class="paagination">
        <a href="#" class="cirlce"></a>
        <a href="#" class="cirlce cirlce-active"></a>
        <a href="#" class="cirlce"></a>
    </div>
</div>
<div class="featured"><a href="#" class="featured-a3">Рекомендуемые</a> <a href="#" class="featured-new">Новые</a>
    <!-- невидимый div-->
    <div class="featured-new2">Новые</div>
    <a href="#" class="explore featured-explore">показать все</a>
    <ul class="featured-product">
        <li class="featured-li">
            <a href="#" class="feature-link feature-list product-1 feature-product"></a>
        </li>
        <li class="featured-li">
            <a href="#" class="feature-link feature-list product-2 feature-product"></a>
        </li>
        <li class="featured-li">
            <a href="#" class="feature-link feature-list product-3 feature-product"></a>
        </li>
        <li class="featured-li">
            <a href="#" class="feature-link feature-list product-4 feature-product"></a>
        </li>
    </ul>
</div>
<div class="exclusive clearfix">
    <div class="left-exclusive">
        <p class="p-exclusive margin-exclusive">бестселлер</p>
        <h3 class="exclusive-h2">Марк Лутц</h3>
        <p class="exclusive-content margin-exclusive">Изучаем Python. 3-е издание</p>
        <a href="{% url 'basket:add_book' 3 %}"
           class="buttom margin-exclusive">
            Заказать
        </a>
    </div>
    <div class="right-exclusive">
        <p class="p-exclusive margin-exclusive">бестселлер</p>
        <h3 class="exclusive-h2">Гарри Поттер</h3>
        <p class="exclusive-content margin-exclusive">Вся серия</p>
        <a href="{% url 'basket:add_book' 2 %}"
           class="buttom margin-exclusive">
            Заказать
        </a>
    </div>
</div>
<div class="trending  clearfix">
    <h3 class="H3 trending-h3">Популярные</h3> <a href="#" class="explore trending-explore">показать все</a>
    <table class="trending-table">
        <tr class="tredding-tr">
            <td class="treding-td">
                <a href="#" class="treding-a"><img src="{% static 'img/product-11.jpg' %}" alt="foto"
                                                   class="treding-img"></a>
            </td>
            <td class="treding-td">
                <a href="#" class="treding-a"><img src="{% static '/img/product-21.jpg' %}" alt="foto"
                                                   class="treding-img"></a>
            </td>
            <td class="treding-td">
                <a href="#" class="treding-a"><img src="{% static 'img/product-31.jpg' %}" alt="foto"
                                                   class="treding-img"></a>
            </td>
        </tr>
        <tr class="tredding-tr">
            <td class="treding-td">
                <a href="#" class="treding-a"><img src="{% static 'img/product-41.jpg' %}" alt="foto"
                                                   class="treding-img"></a>
            </td>
            <td class="treding-td">
                <a href="#" class="treding-a"><img src="{% static 'img/product-5.jpg' %}" alt="foto"
                                                   class="treding-img"></a>
            </td>
            <td class="treding-td">
                <a href="#" class="treding-a"><img src="{% static 'img/product-6.jpg' %}" alt="foto"
                                                   class="treding-img"></a>
            </td>
        </tr>
    </table>
</div>
<div class="hot-deal  clearfix">
    <p class="hot-deal-hot-deal">Горячее предложение</p>
    <h2 class="hot-deal-h2">Скидки 50%</h2>
    <p class="hot-deal-content">Купи пять по цене трех и получи подарок</p> <a href="" class="buttom hot-deal-buttom">Заказать</a>
    <div class="hot-deal-pagination">
        <a href="#" class="cirlce"></a>
        <a href="#" class="cirlce cirlce-active"></a>
        <a href="#" class="cirlce"></a>
    </div>
</div>
<div class="exclusive-second clearfix">
    <table class="exlusive-second-table">
        <tr>
            <td class="exclusive-second-td1" rowspan="2"><img src="{% static 'img/product-1-lg.jpg' %}" alt="foto">
                <p class="exclusive-exclusive-second">издание 1966 года</p>
                <h3 class="h3-exclusive-second">И.А. Гончаров</h3>
                <p class="p-exclusive-second">Полное собрание сочинений</p> <a href="#" class="buttom margin-exclusive">Заказать</a>
            </td>
            <td class="exclusive-second-td">
                <a href="#" class="exclusive-second-link"><img src="{% static 'img/product-2-sm.jpg' %}" alt="foto"
                                                               class="exclusive-second-img"></a>
            </td>
            <td class="exclusive-second-td">
                <a href="#" class="exclusive-second-link"><img src="{% static 'img/product-3-sm.jpg' %}" alt="foto"
                                                               class="exclusive-second-img"></a>
            </td>
        </tr>
        <tr>
            <td class="exclusive-second-td2">
                <a href="#" class="exclusive-second-link"><img src="{% static 'img/product-4-sm.jpg' %}" alt="foto"
                                                               class="exclusive-second-img"></a>
            </td>
            <td class="exclusive-second-td2">
                <a href="#" class="exclusive-second-link"><img src="{% static 'img/product-5-sm.jpg' %}" alt="foto"
                                                               class="exclusive-second-img"></a>
            </td>
        </tr>
    </table>
</div>
<div class="mobule">
    <p class="p-mobule">mobile app</p>
    <h3 class="mobule-h2">Установите наше приложение</h3>
    <p class="mobule-content">Покупайте и читайте в любом месте</p>
    <a href="" class="mobule-app"><img src="{% static 'img/app-store.jpg' %}" alt="link"></a>
    <a href="" class="mobule-google"><img src="{% static 'img/google-play.jpg' %}" alt="link"></a>
</div>

{% endblock %}

my_work/geekshop/mainapp/templates/mainapp/product.html
{% extends 'mainapp/base.html' %}
{% load static %}
{% load my_tags %}

{% block conteiner %}

<div class="slider-contact padding-site clearfix">

    {% include 'mainapp/includes/inc__main_menu.html' %}

    <div class="contact-us-product">Наши книги</div>
</div>

<div class="product-block">
    <div>
        <h3>
            Выберете категорию
        </h3>
    </div>
    <div class="product-menu">

        {% include 'mainapp/includes/inc__catalog_menu.html' %}

    </div>

    <div>
        <h3>книги</h3>
        <div class="paginator">
            {% if books.has_previous %}
            <a href="{% url 'main:catalog_page_pages' genre_pk books.previous_page_number %}">
                <
            </a>
            {% endif %}
            <span class="current">страница {{ books.number }} из {{ books.paginator.num_pages }}</span>
            {% if books.has_next %}
            <a href="{% url 'main:catalog_page_pages' genre_pk books.next_page_number %}">
                >
            </a>
            {% endif %}
        </div>

    </div>

    <div class="row product-catalog">
        {% for item in books %}
        <a href="{% url 'main:product_details' item.id %}">
            <img src="{{ item.image|media_folder_books }}" alt="photo">
        </a>
        {% endfor %}
    </div>
</div>
{% if request.resolver_match.url_name == 'product' %}
<div class="exclusive clearfix">
    <img src="{{ hot_book.image|media_folder_users }}">
    <p class="p-exclusive margin-exclusive">бестселлер</p>
    <h3 class="exclusive-h2">{{ hot_book.author }}</h3>
    <p class="exclusive-content margin-exclusive">{{ hot_book.name }}</p>
    <h3 class="exclusive-h2">{{ hot_book.price }}</h3>
    <a href="{% url 'basket:add_book' hot_book.id %}"
       class="buttom margin-exclusive">
        Заказать
    </a>

</div>

<div class="trending  clearfix">
    <h3 class="H3 trending-h3">Похожие</h3> <a href="#" class="explore trending-explore">показать все</a>
    <table class="trending-table">
        <tr class="tredding-tr">
            {% for item in same_books %}
            <td class="treding-td">
                <a href="{% url 'main:product_details' item.id %}" class="treding-a"><img src="{{ item.image|media_folder_books }}"
                                                                                          alt="photo"
                                                                                          class="treding-img"></a>
            </td>
            {% endfor %}
        </tr>
    </table>
</div>
{% endif %}
<div class="clr"></div>

{% endblock %}

my_work/geekshop/mainapp/templates/mainapp/product_details.html
{% extends 'mainapp/base.html' %}
{% load static %}
{% block conteiner %}
{% load my_tags %}

<div class="slider-contact padding-site clearfix">

    {% include 'mainapp/includes/inc__main_menu.html' %}

    <div class="contact-us-product">Наши книги</div>
</div>
{{ item }}
<div class="product-block">
    <div>
        <h3>
            Выберете категорию
        </h3>
    </div>
    <div class="product-menu">

        {% include 'mainapp/includes/inc__catalog_menu.html' %}

    </div>

    <div class="row product-catalog">
        {% for item in books %}
        <a href="#">
            <img src="{{ item.image|media_folder_books }}" alt="foto">
        </a>
        {% endfor %}
    </div>
</div>
<div class="row details-row">
    <div class="col-6 details-left">
        <div class="main-foto"><img src="{{ item.image|media_folder_books }}" alt="photo"></div>
        <div class="color-foto">
            <div class="color-foto-1 color-foto-left"><a href="#"><img src="{{ item.image|media_folder_books }}" alt="photo"></a>
            </div>
            <div class="color-foto-1"><a href="#"><img src="{{ item.image|media_folder_books }}" alt="photo"></a></div>
            <div class="color-foto-1"><a href="#"><img src="{{ item.image|media_folder_books }}" alt="photo"></a></div>
        </div>
    </div>
    <div class="col-6 details-rigth">
        <div class="details-h2">{{ item.name }}</div>
        <p class="hot-deal-hot-deal details-p">скидки</p>
        <p class="details-p2"><span class="details-span">{{ item.price }}</span>/р</p>
        <a href="{% url 'basket:add_book' item.id %}" class="details-buttom">Купить</a>
        <p class="hot-deal-content">
            {{ item.description }}
        </p>
    </div>
</div>


<div class="clr"></div>

{% endblock %}